Task_1_1_1
Routybor/OOP pull request #1
Opened 2024-09-05 02:52 UTC by Routybor

2024-09-05 02:55 UTC, Routybor commented
Яхимович Даниил 23214

2024-09-05 03:22 UTC, Routybor commented
Про последний пункт задания с практической сложностью алгоритма.
Я попробовал прикинуть сложность 2 способами.

Первый представлен в самом main/java/Heapsort.java
iterationCount1 и iterationCount2 добавил в 2 основных цикла(на больших N - iterationCount1 можно принебречь).
Добавил вычисление предполагаемой величины. Всё это выводится в консоль, можно увидеть, что кол-во итераций не превышает ожидания.

В юнит тесте 2 попытался прикинуть по времени выполнения программы.
Сделал 2 больших массива, заполнил случайными числами и сверил с функцией сортировки из библиотеки.
Из википедии:
![image](https://github.com/user-attachments/assets/efec25aa-ec4f-40a3-bee6-260f7387a862)
Константа неизвестна. Я решил сранить отношение времени выполнения влгоритма при N1 и N2 и отношение предполагаемой сложности N1 к сложности при N2.
Все вычисления выводятся в консоль. Так как массивы при каждом запуске программы меняются - меняется и время выполнения сортировки, из-за этого отношении времени выполнения немного плавает.

2024-09-09 10:36 UTC, shadrina requested changes

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/build.gradle
> +group = 'org.example'
Напиши пакет в соответствии с формой, рекомендуемой Google Style Guide.

Например, `ru.nsu.surname`, так как сейчас ты студент НГУ. Далее это будет домен организации, в которой работаешь.

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/launch.sh
> +javadoc -d doc src/main/java/HeapSort.java
Это работает? Файл называется иначе.

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/src/main/java/Heapsort.java
> +/**
В Java нужен пакет (способ задания пространства имен в Java, см. спецификацию или интернет). Иначе имена твоих классов могут клэшиться с именами классов сторонних библиотек.

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/src/main/java/Heapsort.java
> +/**
Компилятор его ставить не обязывает, но в любом неигрушечном проекте он нужен. Особенно если проект планирует публиковаться/распространяться.

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/src/main/java/Heapsort.java
> +        System.out.println("===== HEAPSORT INITIATED =====");
Получается, при запуске приложения с точки входа (а не из тестов) ничего не происходит, только пишется строка в консоль. Для задачи main в целом не требуется, но раз сделал, пусть он считывает массив с консоли и делает heapsort на нем.

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/src/test/java/UnitTest.java
> +    void heapsort_one_elem_test() {
В Java мы используем только camelCase. См. Google Style Guide.

2024-09-09 10:36 UTC, shadrina commented on Task_1_1_1/src/test/java/UnitTest.java
> +        System.out.println("===== TEST 2 =====");
Это необязательно. При необходимости такое делается специальными методами используемой библиотеки для тестирования.

2024-09-09 10:38 UTC, shadrina commented
> Про последний пункт задания с практической сложностью алгоритма. Я попробовал прикинуть сложность 2 способами.
> 
> Первый представлен в самом main/java/Heapsort.java iterationCount1 и iterationCount2 добавил в 2 основных цикла(на больших N - iterationCount1 можно принебречь). Добавил вычисление предполагаемой величины. Всё это выводится в консоль, можно увидеть, что кол-во итераций не превышает ожидания.
> 
> В юнит тесте 2 попытался прикинуть по времени выполнения программы. Сделал 2 больших массива, заполнил случайными числами и сверил с функцией сортировки из библиотеки Arrays. Из википедии: ![image](https://private-user-images.githubusercontent.com/71870000/364610646-efec25aa-ec4f-40a3-bee6-260f7387a862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzg1MDMsIm5iZiI6MTcyNTg3ODIwMywicGF0aCI6Ii83MTg3MDAwMC8zNjQ2MTA2NDYtZWZlYzI1YWEtZWM0Zi00MGEzLWJlZTYtMjYwZjczODdhODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTQ2NjZmYzM1Y2IwMTU1YjNlMzhmMTNlY2ZhNjcyN2FhYmZkOWNiMzM4ZjhhYmIzNTJkNjA0ZWE2NWQ1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lE5zl-zDV7HxfXkGbnd9CUNcCbsJgZkaWeIMJu3ukkw) Константа неизвестна. Я решил сранить отношение времени выполнения влгоритма при N1 и N2 и отношение предполагаемой сложности N1 к сложности при N2. Все вычисления выводятся в консоль. Так как массивы при каждом запуске программы меняются - меняется и время выполнения сортировки, из-за этого отношении времени выполнения немного плавает.

Ты все правильно сделал. Неважно, что константа неизвестна. Наша задача - из полученных цифр увидеть функцию/график/зависимость, который и будет NlogN, если все сделано верно.

2024-09-09 14:09 UTC, Routybor commented on Task_1_1_1/build.gradle
> +group = 'org.example'
Понял, добавил

2024-09-09 14:10 UTC, Routybor commented on Task_1_1_1/launch.sh
> +javadoc -d doc src/main/java/HeapSort.java
Понял, забыл, исправил

2024-09-09 14:10 UTC, Routybor commented on Task_1_1_1/src/main/java/Heapsort.java
> +/**
Понял, добавил

2024-09-09 14:10 UTC, Routybor commented on Task_1_1_1/src/main/java/Heapsort.java
> +        System.out.println("===== HEAPSORT INITIATED =====");
Понял, сделал. Немного тривиально с размером массива, но зато быстро)

2024-09-09 14:12 UTC, Routybor commented on Task_1_1_1/src/test/java/UnitTest.java
> +        System.out.println("===== TEST 2 =====");
Хорошо

2024-09-09 14:12 UTC, Routybor commented on Task_1_1_1/src/test/java/UnitTest.java
> +    void heapsort_one_elem_test() {
Понял, исправил.

2024-09-09 14:19 UTC, Routybor commented on Task_1_1_1/src/main/java/Heapsort.java
> +        System.out.println("===== HEAPSORT INITIATED =====");
Понял, сделал. Теперь на покрытие ругается, что делать дальше??

2024-09-09 14:20 UTC, Routybor commented on Task_1_1_1/launch.sh
> +javadoc -d doc src/main/java/HeapSort.java
Понял, подзабыл, поправил.

2024-09-09 14:20 UTC, Routybor commented on Task_1_1_1/build.gradle
> +group = 'org.example'
Понял, добавил.

2024-09-09 14:38 UTC, Routybor commented on Task_1_1_1/src/main/java/Heapsort.java
> +        System.out.println("===== HEAPSORT INITIATED =====");
Я добавил, но теперь покрытия чутка не хватает. Мне удалить вовсе или проигнорить 5% покрытия?

2024-09-10 07:54 UTC, shadrina approved these changes

2024-09-10 07:54 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/yakhimovich/UnitTest.java
> +public class UnitTest {
Обычно в Java называем тест, который тестирует класс A `ATest`. Обычно классов много, на каждый класс будут свои юнит-тесты

2024-09-10 08:22 UTC, Routybor commented
![image](https://github.com/user-attachments/assets/be3cad58-8e1f-4089-9e3d-a6057f641e9b)
[Complexity.xlsx](https://github.com/user-attachments/files/16941804/Complexity.xlsx)

2024-09-10 08:40 UTC, shadrina approved these changes

2024-09-10 08:41 UTC, merged