Task_1_1_2
Routybor/OOP pull request #2
Opened 2024-09-12 04:51 UTC by Routybor

2024-09-12 06:31 UTC, Routybor commented
Нормальную проверку на покрытие проблематично сделать, так как большАя часть кода связанна с тузами. Таким образом если тузы не выпадают, в ходе теста - покрытия не хватает.

2024-09-18 11:29 UTC, shadrina reviewed
Если оно еще и работает, то мне все нравится. 

Единственное, не хватает тестов.

2024-09-18 11:30 UTC, shadrina commented
> Нормальную проверку на покрытие проблематично сделать, так как большАя часть кода связанна с тузами. Таким образом если тузы не выпадают, в ходе теста - покрытия не хватает.
> 
> Если в данной задаче это критично, подумаю над лучшими тестами.

Так сделай пару тестов, где тузы выпадают? Один отдельный тест не обязан покрывать весь код, покрытие считается общее.

2024-09-18 12:13 UTC, Routybor commented
Не проблематично в итоге)

Когда изначально делал, не мог произвести несколько раундов в юнит тесте, потому что после первого раунда опустошался ввод программы и она падала. Попробовал тогда добавлять строку в поток ввода в цикле, не получалось. Оказывается там есть метод reset, с ним работает.

За 10 раундов выпадает всё что только можно и покрытия хватает.

2024-09-23 11:41 UTC, shadrina requested changes

2024-09-23 11:41 UTC, shadrina commented on Task_1_1_2/launch.sh
> +java -cp build ru.nsu.yakhimovich.Blackjack
С этой лабы и далее этим уже не надо заниматься, удаляй.
Мы просто так поняли минимум, который делает gradle.

2024-09-23 11:41 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/yakhimovich/Blackjack.java
> +package ru.nsu.yakhimovich;
По поводу именований пакетов скажу на паре.

2024-09-23 11:41 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/yakhimovich/Deck.java
> +                          "Восьмерка", "Девятка", "Десятка", "Валет", "Королева", "Король", "Туз"};
Исправлять не надо, просто для информации.
В ОО-стиле тут напрашиваются [enum'ы](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html).

2024-09-23 11:41 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/yakhimovich/Deck.java
> +            return null; // Такое состояние не должно возникать в данных условиях
Инварианты можно программировать с помощью конструкции [assert](https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html)

2024-09-23 11:41 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/yakhimovich/Hand.java
> +        }
Вот если бы ты сделал enum'ы, этот метод бы значительно преобразился с точки зрения читаемости.

2024-09-23 11:41 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/yakhimovich/BlackjackUnitTest.java
> +public class BlackjackUnitTest {
Тут нет unit-тестов. Это наши условия. Есть 4 класса, у каждого методы с определенным контрактом, контракт должен валидироваться в тестах.

2024-09-23 17:15 UTC, Routybor commented on Task_1_1_2/src/main/java/ru/nsu/yakhimovich/Deck.java
> +                          "Восьмерка", "Девятка", "Десятка", "Валет", "Королева", "Король", "Туз"};
Хорошо

2024-09-23 17:16 UTC, Routybor commented on Task_1_1_2/src/test/java/ru/nsu/yakhimovich/BlackjackUnitTest.java
> +public class BlackjackUnitTest {
Сделал

2024-09-24 08:31 UTC, shadrina approved these changes
Читать про статик

2024-09-24 08:44 UTC, merged