Task_1_1_3
Routybor/OOP pull request #3
Opened 2024-09-20 10:46 UTC by Routybor

Сделал доп задание.

1) Парсинг у меня с реализацией на вещественных числах (поддержка отрицательных чисел, не переменных). Ошибки неверного формата строки вроде все отловил.

2) Немного расширил список упрощений. Деление нуля, деление равных, сумма с нулём, сумма с противоположным.

2024-10-07 11:35 UTC, shadrina requested changes

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Div.java
> +    private final ru.nsu.yakhimovich.expression.Expression right;
import?

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Div.java
> +        }
А 3 / 0 сюда не попадет? Под условие подходит

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Expression.java
> +    public abstract void print(); // Печать выражения
Что-то мне подсказывает, что реализация везде одинаковая.

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +    private static String input;
Я бы сделала обычное состояние, не статическое. Не вижу, какие здесь преимущества от того, что все статическое. Обычный класс с обычным состоянием.

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +                    || input.charAt(ind) == '*' || input.charAt(ind) == '/') {
Здесь очень просятся:
1) `final var currentChar = input.charAt(ind)`
2) `isOperator(char)`

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +                throw new RuntimeException("Некорректный ввод= повторные/завершающие операторы!");
Don't Repeat Yourself. Идея должна все это подсвечивать.

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +                    || input.charAt(ind) == '*' || input.charAt(ind) == '/') {
Ну и, конечно, в идеале enum Operator...

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Mul.java
> +    }
Пророчество сбывается

2024-10-07 11:35 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Variable.java
> +    public boolean equals(Object obj) {
При перегрузке equals мы всегда перегружаем hashCode. Вопрос к тебе на сдачу: почему?

2024-10-07 14:16 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Div.java
> +        }
Вообще хотел это фичей сделать, программа не падает, а дает бесконечность, но из-за этого слишком много нюансов -> добавил ошибку.

2024-10-07 14:17 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Expression.java
> +    public abstract void print(); // Печать выражения
Онет. Лишние реализации убрал.

2024-10-07 14:21 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +    private static String input;
Я бы тоже обычное состояние сделал, но в таком случае перестаёт работать - повсюду статические методы.

2024-10-07 14:21 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +                    || input.charAt(ind) == '*' || input.charAt(ind) == '/') {
Окей, поменял

2024-10-07 14:22 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +                throw new RuntimeException("Некорректный ввод= повторные/завершающие операторы!");
Поменял. Идея предательски молчит)

2024-10-07 14:22 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Mul.java
> +    }
ага

2024-10-07 14:23 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Variable.java
> +    public boolean equals(Object obj) {
✍️

2024-10-14 12:46 UTC, shadrina requested changes

2024-10-14 12:46 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Add.java
> +    public Expression simplify() {
Не надо звать eval внутри simplify. Просто сделай возможность брать у числа его значение.

2024-10-14 12:46 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Div.java
> +    private final ru.nsu.yakhimovich.expression.Expression right;
Зачем полная квалификация?

2024-10-14 12:46 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Div.java
> +        ru.nsu.yakhimovich.expression.Expression simpleRight = right.simplify();
Аналогичные замечания замечаниям выше

2024-10-15 02:09 UTC, Routybor commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +            if (sb.length() == 0) {
Из-за этого я и не использовал isEmpty

![Screenshot 2024-10-15 090131](https://github.com/user-attachments/assets/a16d2833-ab5c-4e4d-be86-a6a89e397762)

2024-10-15 14:49 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/ExpressionParser.java
> +            if (sb.length() == 0) {
Потому что у тебя версия Java не выставлена в build.gradle. Чтобы метод появился, нужна версия >= 15. + я тебя попросила не использовать eval в simplify, т.е. доставать из Number значение напрямую. Для этого понадобится еще одна фича, которая требует повышения версии Java -- pattern matching.

2024-10-29 07:53 UTC, shadrina requested changes

2024-10-29 07:53 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/yakhimovich/expression/Div.java
> +        if (simpleLeft instanceof Number && ((Number) simpleLeft).getValue() == 0) {
`if (simpleLeft instanceof Number simpleLeftNumber && simpleLeftNumber.getValue() == 0)`

2024-11-05 05:44 UTC, shadrina requested changes
По задаче все ок, но я не могу принять PR с правками в других задачах и ругающимся reviewdog

2024-11-12 08:44 UTC, shadrina approved these changes

2024-11-13 10:11 UTC, merged