Task_1_2_1
Routybor/OOP pull request #4
Opened 2024-10-22 11:25 UTC by Routybor

2024-10-29 08:24 UTC, shadrina requested changes
В остальном все ОК

2024-10-29 08:24 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakhimovich/graph/AdjacencyListGraph.java
> +import java.util.*;
Ну отключи ты этот варнинг

2024-10-29 08:24 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakhimovich/graph/Graph.java
> +        Stack<String> stack = new Stack<>();
Используй, пожалуйста, java.util.Deque. Стек старый и синхронизованный

2024-10-29 08:24 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakhimovich/graph/Graph.java
> +public interface Graph {
Граф должен быть параметризованным

2024-10-29 08:24 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakhimovich/graph/Graph.java
> +    void readFromFile(String fileName) throws IOException;
И соответстветственно, раз узел может иметь разный тип, вот тут понадобится параметр функционального типа, который будет парсить строковое представление вершины.

2024-11-05 06:10 UTC, shadrina requested changes

2024-11-05 06:10 UTC, shadrina commented on .github/google_checks.xml
> +    <!-- <module name="AvoidStarImport"/> -->
Давай отдельным PR

2024-11-05 06:10 UTC, shadrina commented on .github/google_checks.xml
> +    <!-- <module name="AvoidStarImport"/> -->
Тут не надо, это не имеет отношения к задаче про граф

2024-11-05 06:10 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/yakhimovich/graph/AbstractGraphTest.java
> +    protected Graph<T> graph;
В тесте-то зачем параметризация?

2024-11-05 06:10 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/yakhimovich/graph/AbstractGraphTest.java
> +     * Преобразование строки в объект типа T.
Не надо... Просто тестируй конкретные классы с известным означиванием типовых параметров.

2024-11-05 06:10 UTC, shadrina commented on Task_1_2_1/src/test/resources/test.txt
> +C D
Хотелось бы тестов с разными типами у вершин

2024-11-18 11:48 UTC, shadrina requested changes

2024-11-18 11:48 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakhimovich/graph/AdjacencyMatrixGraph.java
> +    }
Сильно отличаются три реализации?

2024-11-18 11:48 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakhimovich/graph/Graph.java
> +    default void topologicalSortUtil(T vertex, Set<T> visited, Deque<T> stack) {
Вообще планировалось, что вы сделаете отдельную иерархию для алгоритмов на графах, но раз так сделал, то хотя бы запривать этот метод. Это внутренние детали реализации топсорта, они никак не касаются конкретных реализаций графа.

2024-11-26 09:03 UTC, Routybor commented
Извиняюсь, совсем забыл про это задание

2024-12-03 08:05 UTC, shadrina requested changes

2024-12-03 08:05 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/yakhimovich/graph/integer/AbstractIntGraphTest.java
> +        graph.readFromFile("src/test/resources/test2.txt", Integer::valueOf);
Взорвется при исполнении JAR'а в другой директории

2024-12-17 08:02 UTC, shadrina approved these changes

2024-12-24 04:37 UTC, merged